apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eventstore-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eventstore-db
    spec:
      containers:
        - name: eventstore-node
          image: eventstore/eventstore
          ports:
            - containerPort: 2113
            - containerPort: 2114
            - containerPort: 1113
            - containerPort: 1112
        - name: hello-world
          image: crccheck/hello-world
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: eventstore-db
spec:
  ports:
    - name: http-port
      protocol: TCP
      port: 8113
      targetPort: 2113
    - name: com-port
      protocol: TCP
      port: 7113
      targetPort: 1113
    - name: hw-port
      protocol: TCP
      port: 8001
      targetPort: 8000  
  selector:
    app: eventstore-db
  
---
apiVersion: extensions/v1beta1
kind: Ingress

metadata:
  name: eventstore-db

spec:
  backend:
    serviceName: default-http-backend
    servicePort: 80
  rules:
    - host: eventstore.local
      http:
        paths:
          - path: /
            backend:
              serviceName: eventstore-db
              servicePort: 8001